//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int Emp_ID { get; set; }
        public string Emp_name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Emp_Department { get; set; }
        public string Emp_Position { get; set; }
        public Nullable<int> Emp_Age { get; set; }
        public Nullable<decimal> Emp_salary { get; set; }
        public Nullable<int> Emp_LeaveBalance { get; set; }
        public string Image { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Race { get; set; }
        public string Religion { get; set; }
        public string NRIC { get; set; }
        public string Nationality { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
    }
}
