//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leavework
    {
        public int Leave_Id { get; set; }
        public string Leave_Status { get; set; }
        public System.DateTime Leave_Date { get; set; }
        public System.DateTime Leave_EndDate { get; set; }
        public string Leave_Desc { get; set; }
        public string Emp_name { get; set; }
        public string Leave_Type { get; set; }
    }
}
